domain:
  http: http://localhost:3000
  https: https://localhost:3000

twelvedata:
  api:
    url: https://api.twelvedata.com/

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mocket
  threads:
    virtual:
      enabled: true